name: .NET Test

permissions:
  contents: read

on:
  # Required for reusable workflows.
  workflow_call:
    inputs:
      source-directory:
        description: The directory (to the solution or project) to build.
        type: string
        default: src

      global-json-path:
        description: The path to the global.json file, this will determine the .NET version to install and use.
        type: string
        default: src/global.json

      configuration:
        description: The configuration to run the build with.
        type: string
        required: true

      machine-type:
        description: The type of the machine to run the workflow on.
        type: string
        default: ubuntu-latest

jobs:
  test:
    runs-on: ${{ inputs.machine-type }}

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v5
        with:
          sparse-checkout: ${{ inputs.source-directory }}

      - name: Setup the .NET development environment.
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: ${{ inputs.global-json-path }}
          cache: true
          cache-dependency-path: "**/packages.lock.json"

      - name: Restore the project dependencies.
        working-directory: ${{ inputs.source-directory }}
        run: dotnet restore --locked-mode

      - name: Build the source directory.
        working-directory: ${{ inputs.source-directory }}
        run: dotnet build --no-restore --configuration ${{ inputs.configuration }}

      - name: Run the tests.
        working-directory: ${{ inputs.source-directory }}
        run: dotnet test --no-build --configuration ${{ inputs.configuration }} --warnaserror
