name: .NET Build

permissions:
  contents: read

on:
  # Required for reusable workflows.
  workflow_call:
    inputs:
      dotnet-version:
        description: The .NET version to install.
        type: string
        default: '9'

      configuration:
        description: The configuration to run the build with.
        type: string
        required: true

      source-directory:
        description: The directory (to the solution or project) to build.
        type: string
        default: src

      machine-type:
        description: The type of the machine to run the workflow on.
        type: string
        default: ubuntu-latest

jobs:
  build:
    runs-on: ${{ inputs.machine-type }}

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v5
        with:
          sparse-checkout: ${{ inputs.source-directory }}

      - name: Setup the .NET development environment.
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          cache: true
          cache-dependency-path: "**/packages.lock.json"

      - name: Restore the project dependencies.
        working-directory: ${{ inputs.source-directory }}
        run: dotnet restore --locked-mode

      - name: Build the source directory.
        working-directory: ${{ inputs.source-directory }}
        run: dotnet build --no-restore --warnaserror --configuration ${{ inputs.configuration }}
